HttpConnectionMockTest: work around ambiguous class name problem
Due to https://github.com/groovy/groovy-eclipse/issues/1354, without an
explicit import for java.net.Proxy, there will be a compilation error:

"The type Proxy is ambiguous"